[project]
name = "iotbay-api"
version = "0.0.1"
description = "Flask backend for IoTBay"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "babel>=2.18.0",
    "certifi>=2026.2.25",
    "flask>=3.1.3",
    "phonenumbers>=9.0.28",
    "pydantic>=2.13.3",
    "pydantic-settings>=2.14.0",
]

[tool.uv]
managed = true
dev-dependencies = [
    "ruff>=0.15.11",
    "pyright>=1.1.408",
]

[tool.ruff]
line-length = 88
target-version = "py314"
src = ["src", "tests"]
extend-exclude = [".venv"]

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.lint.pycodestyle]
ignore-overlong-task-comments = true
